export { db } from "./client.ts";
export * from "./schema.ts";
export {
  SESSION_ARTIFACT_KINDS,
  type SessionArtifactKind,
  type SessionArtifactRef,
  type SessionArtifactWrite,
} from "./artifacts.ts";
export {
  formatTranscriptForDisplay,
  formatTranscriptForInference,
  simplifyTranscript,
  type Transcript,
  type TranscriptSegment,
  type TranscriptTurn,
} from "./transcript.ts";
export {
  createCampaign,
  addCampaignMember,
  removeCampaignMember,
  type CreateCampaignInput,
  type AddCampaignMemberInput,
} from "./campaigns.ts";
export {
  getCampaignsForGuild,
  getCampaignsForUser,
  isAdmin,
  isCampaignMember,
  getCampaignMeta,
  getCampaignCast,
  getCampaignDetail,
  getSessionDetail,
  type CampaignMember,
  type CampaignCastMember,
  type CampaignSessionSummary,
  type CampaignDetail,
  type SessionDetail,
} from "./queries.ts";
export {
  beginClosingSession,
  claimAggregationIfReady,
  claimProcessingRuns,
  completeProcessingRun,
  completeSegmentTranscription,
  createRecordingSession,
  failProcessingRun,
  failSegmentTranscription,
  finishClosingSession,
  getAudioSegmentRefs,
  getAudioSegmentsForRecovery,
  getProcessingRun,
  getRecoverableSessionsForGuild,
  getTranscriptSegments,
  hasOpenRecordingForGuild,
  listAudioPendingDeletion,
  listSegmentsForTranscription,
  markNotificationComplete,
  markNotificationFailed,
  markSegmentDiscarded,
  markSegmentAudioDeleted,
  markSegmentAudioFailed,
  markSegmentReady,
  markTranscriptionProcessing,
  registerRecordingSegment,
  releaseProcessingRun,
  renewProcessingRunLease,
  startInferenceRegeneration,
  startTranscriptRegeneration,
  storeAggregatedTranscript,
  storeRunDetailedRecord,
  storeRunRecap,
  storeRunTitle,
  type AudioSegmentRef,
  type CreateRecordingSessionInput,
  type ProcessingRunData,
  type RecoverableSession,
  type SegmentForTranscription,
} from "./processing.ts";
